#!/usr/bin/env bash

# install git
sudo yum install git -y
# check version
git --version 

# install Go
sudo yum install golang -y
# check version
go --version 

# install Node and npm
curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
sudo yum install nodejs -y
# check version
node --version
npm --version

# install Vue cli
yes | npm install -g @vue/cli
# check version
vue --version


# clone the test application 
git clone https://github.com/jdmendozaa/vuego-demoapp.git

# build the Go project
cd vuego-demoapp/server
go build

# share the files to the shared folder
cd
cp /home/vagrant/vuego-demoapp/server/vuego-demoapp /shared/ 

# define  the env variables
echo 'export PORT=4001' >> /etc/profile
sudo echo 'VUE_APP_API_ENDPOINT="http://10.0.0.8:4001/api"' >> /home/vagrant/vuego-demoapp/spa/.env.production.local

# build the Vue app
cd home/vagrant/vuego-demoapp/spa
sudo npm install 
npm run build

# To compress dist folder generated by Vue build and move it to shared folder
tar -zcvf dist.tar.gz ./dist
mv dist.tar.gz /shared/
